### PR TITLE
A Modest Proposal

### PR DESCRIPTION
**Pull request by wastella**
Pog sup lerbiq

### CODE REVIEW

**Comment by Lerbiq** [comment]
Make sure that the `end_universe` function is at the end of the source file. The universe might break in runtime since the compiler is so janky

**Comment by wastella** [comment]
ah yes, the universe might not compile, aight gatchu

**Comment by wastella** [comment]
well, you called end_universe, start_universe, and run_universe, but they were not defined yet, I put main at the end

**Comment by Lerbiq** [comment]
I checked the original Hebrew code and it seems right, thanks

**Pull request merged**
